# Generated by Django 4.0.4 on 2022-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosfisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('km', models.IntegerField()),
                ('est', models.IntegerField()),
                ('magnitud', models.CharField(max_length=100)),
                ('medida', models.FloatField(default=0.0)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='individuomedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('nind', models.IntegerField()),
                ('LargoTotal', models.FloatField(default=0.0)),
                ('peso', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('km', models.IntegerField()),
                ('est', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='obscasuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('nind', models.IntegerField()),
                ('date', models.DateField()),
                ('obs', models.CharField(max_length=150)),
            ],
        ),
    ]
